apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - ingress.yaml
  - backend-servicemonitor.yaml
  - grafana-tempo-datasource.yaml
  - otel-collector-http-service.yaml
  - otel-collector-ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: grafana-app-dashboard
    files:
      - app-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
