services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    environment:
      VITE_API_URL: http://localhost:3001/api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
    depends_on:
      - backend
      - tempo

  backend:
    build: ./backend
    ports:
      - "3001:80"
    environment:
      REDIS_URL: redis://redis:6379
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4318
      OTEL_SERVICE_NAME: backend-service
    depends_on:
      - redis
      - tempo

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    volumes:
      - redisinsight_data:/data
    environment:
      RI_REDIS_HOST_LOCAL: redis
      RI_REDIS_PORT_LOCAL: 6379
    depends_on:
      - redis

  # Tempo para almacenar trazas
  tempo:
    image: grafana/tempo:latest
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/tmp/tempo
    ports:
      - "3200:3200"   # Tempo UI
      - "4317:4317"   # OTLP gRPC
      - "4318:4318"   # OTLP HTTP

  # Grafana para visualizar trazas
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3030:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - grafana-data:/var/lib/grafana
    depends_on:
      - tempo

volumes:
  redisdata:
  redisinsight_data:
  tempo-data:
  grafana-data: