apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: app
data:
  VITE_API_URL: "http://20.42.47.137/api"
  VITE_OTEL_ENDPOINT: "http://20.42.47.137/otel/v1/traces"
  REDIS_URL: "redis://redis.app.svc.cluster.local:6379"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://20.42.47.137/otel/v1/traces"
