apiVersion: v1
kind: Service
metadata:
  name: redis-insight
  namespace: app
  labels:
    app: redis-insight
spec:
  type: NodePort
  selector:
    app: redis-insight
  ports:
    - name: http
      port: 5540
      targetPort: 5540
      nodePort: 30540
